"""职业名翻译模块"""

CLASS_NAME_MAP: dict[str, str] = {
    "hero": "英雄",
    "dark knight": "黑骑士",
    "paladin": "圣骑士",
    "ice/lightning archmage": "冰雷魔导师",
    "arch mage (i/l)": "冰雷魔导师",
    "fire/poison archmage": "火毒魔导师",
    "arch mage (f/p)": "火毒魔导师",
    "bishop": "主教",
    "shadower": "侠盗(刀飞)",
    "night lord": "隐士(镖飞)",
    "blade master": "暗影双刀",
    "buccaneer": "冲锋队长",
    "corsair": "船长",
    "cannon master": "神炮王",
    "marksman": "箭神",
    "bowmaster": "神射手",
    "bow master": "神射手",
    "pathfinder": "古迹猎人",
    "dawn warrior": "魂骑士",
    "blaze wizard": "炎术士",
    "wind archer": "风灵使者",
    "night walker": "夜行者",
    "thunder breaker": "奇袭者",
    "mihile": "米哈尔",
    "xenon": "尖兵",
    "battle mage": "幻灵斗师",
    "wild hunter": "豹弩游侠",
    "mechanic": "机械师",
    "demon slayer": "恶魔猎手",
    "demon avenger": "恶魔复仇者",
    "blaster": "爆破手",
    "aran": "战神",
    "evan": "龙神",
    "mercedes": "双弩精灵",
    "phantom": "幻影",
    "shade": "隐月",
    "luminous": "夜光法师",
    "kaiser": "狂龙战士",
    "kain": "该隐",
    "cadena": "卡德娜",
    "angelic buster": "爆莉萌天使",
    "adele": "阿黛尔",
    "illium": "伊利温",
    "ark": "亚克",
    "khali": "卡莉",
    "lara": "菈菈",
    "hoyoung": "虎影",
    "ren": "莲",
    "hayato": "剑豪",
    "kanna": "阴阳师",
    "zero": "神之子",
    "kinesis": "超能力者",
    "lynn": "琳恩",
    "mo xuan": "墨玄",
    "sia astelle": "施亚",
}

CLASS_ID_MAP: dict[int, str] = {
    1: "Warrior",
    2: "Magician",
    3: "Bowman",
    4: "Thief",
    5: "Pirate",
    10: "Noblesse",
    11: "Dawn Warrior",
    12: "Blaze Wizard",
    13: "Wind Archer",
    14: "Night Walker",
    15: "Thunder Breaker",
    20: "Legend",
    21: "Aran",
    22: "Evan",
    23: "Mercedes",
    24: "Phantom",
    30: "Citizen",
    31: "Demon Slayer",
    32: "Battle Mage",
    33: "Wild Hunter",
    35: "Mechanic",
    113: "Hero",
    123: "Paladin",
    133: "Dark Knight",
    201: "Jett",
    202: "Mihile",
    203: "Luminous",
    204: "Kaiser",
    205: "Angelic Buster",
    206: "Hayato",
    207: "Kanna",
    208: "Xenon",
    209: "Demon Avenger",
    210: "Zero",
    211: "Beast Tamer",
    212: "Shade",
    213: "Fire/Poison",
    214: "Kinesis",
    215: "Blaster",
    216: "Cadena",
    217: "Illium",
    218: "Ark",
    219: "Pathfinder",
    220: "Hoyoung",
    221: "Adele",
    222: "Kain",
    223: "Lara",
    224: "Khali",
    225: "Lynn",
    226: "Mo Xuan",
    227: "Sia Astelle",
}


def translate_class_name(s: str) -> str:
    """将英文职业名翻译成中文"""
    if not s:
        return ""
    return CLASS_NAME_MAP.get(s.lower(), s)


def translate_class_id(class_id: int) -> str:
    """根据职业 ID 翻译成中文职业名"""
    if name := CLASS_ID_MAP.get(class_id):
        return translate_class_name(name)
    if name := CLASS_ID_MAP.get(class_id // 100):
        return translate_class_name(name)
    return ""

